#!/bin/bash

# © 2012-2013 fsckd <fsckdaemon@gmail.com>

## Load config file ##

config=/etc/awbot.conf

# source config if exists and readable
[[ -f "$config" ]] && [[ -r "$config" ]] && source "$config"

## Arguments ##

# function to print unhelpful usage error and then exit
usage_error() { echo "error: incorrect usage, please see manual" >&2 ; exit 1 ; }

# loop over parameters
while (( "$#" ))
do
  # parse config options
  IFS='=' read option value <<<"$1"
  if grep -q @"$option"@ <<<"@server@port@nicks@nick@pass@ircname@ircuser@channel@welcome@notify@seenlist@"
  then
    [[ -z "$value" ]] && [[ "$option" != pass ]] && usage_error
    eval "$1" # set value
  else
    usage_error
  fi
  shift
done

## Verify Config ##

[[ -n "$nick" ]]     && nicks="$nick"
[[ -z "$ircuser" ]]  && ircuser="$nicks"
[[ -z "$server" ]]   ||
[[ -z "$port" ]]     ||
[[ -z "$nicks" ]]    ||
#[[ -z "$pass" ]]     ||
[[ -z "$ircname" ]]  ||
[[ -z "$welcome" ]]  ||
#[[ -z "$notify" ]]   ||
[[ -z "$seenlist" ]] ||
[[ -z "$channel" ]]  &&
{ echo error: configuration is incomplete >&2 ; exit 1 ; }

# do we have access to $seenlist?
if [[ -e "$seenlist" ]]
then
  if ! [[ -f "$seenlist" ]] || ! [[ -r "$seenlist" ]] || ! [[ -w "$seenlist" ]]
  then echo error: file "'$seenlist'" not accessible >&2 ; exit 1
  fi
else
  touch "$seenlist" &>/dev/null || { echo error: can not create file "'$seenlist'" >&2 ; exit 1 ; }
fi


## IRC Bot ##

# References:
# RFCs   - http://irchelp.org/irchelp/rfc/
# colors - http://cpansearch.perl.org/src/HINRIK/IRC-Utils-0.12/lib/IRC/Utils.pm
# and loads of experimenting and testing
# there are *a lot* of assumptions made

cacert=/etc/ssl/certs/ca-certificates.crt # cert file
capath=/etc/ssl/certs # path to ca files

greet() # the greeter function
{
  # $mname - the nick of whom we're greeting
  # $channel - the channel to watch
  # $welcome - the welcome message, it is an array with each element a single line
  # $notify - array of nicks to PM if a new nick enters the channel
  # $seenlist - file containing list of nicks seen

  # don't continue if nick is known
  grep -qs "$mname" "$seenlist" && return

  # send PMs to interested parties
  for n in "${notify[@]}"
  do ircwrite "privmsg $n :new person $mname in $channel"
  done

  # send welcome message
  for m in "${welcome[@]}"
  do
    # replace string %nick% with nick of person being greeted
    m="`sed "s@%nick%@$mname@g" <<<"$m"`"
    ircwrite "privmsg $channel :$m"
    sleep 0.5s
  done

  # remmeber nick for next time
  echo "$mname" >> "$seenlist"
}

ircwrite() # write each arg as a line to irc
{
  while (( "$#" ))
  do
    echo "$1" >&${irc[1]}
    #echo "$1" >> awbot.out.log # DEBUG
    shift
  done
}

enclose01() # remove surrounding \x01, useful for CTCP
{
  # $1 - strip | add - strip surrounding \x01 or add them
  # $2 - string to opperate on

  case $1 in
    strip) tr -d '\001' <<<"$2" # we are lazy
           ;;
      add) echo -e "\\x01$2\\x01" # doubly so
  esac
}

ircmsg() # decompose an IRC message
{
  # RFCs 1459 and 2812

  unset mprefix mname muser mhost mcmd mparam mtrailing

  local queue="$(tr -d '\r' <<<"$line")" # remainder of the line to "parse"
                                         # right now it's the whole line
                                         # minus any \r

  if [[ "$queue" =~ ^: ]]
  then
    # we has a prefex
    queue="${queue#:}" # remove leading :
    ircmsgbreak ' ' mprefix queue # extract prefix!

    # break up the prefix into name, user and host
    local pqueue="$mprefix" # prefix queue XD
    ircmsgbreak '!' mname pqueue # extract name
    [[ -n "$pqueue" ]] && ircmsgbreak '@' muser pqueue # extract user
    [[ -n "$pqueue" ]] && mhost="$pqueue" # extract host
  fi

  [[ -z "$queue" ]] && return # if queue is blank, we're finished here

  # get command
  ircmsgbreak ' ' mcmd queue

  # extract message parameters
  # RFC 2812 says up to 15 parameters
  local tmpstr=""
  mtrailing=false
  for i in `seq 0 14`
  do
    [[ -z "$queue" ]] && return # yup yup yup

    if [[ "$queue" =~ ^: ]]
    then
      # we has a tail (see RFC)
      mparam[$i]="${queue#:}" # remove leading :
      mtrailing=true
      return # we're done
    fi

    ircmsgbreak ' ' tmpstr queue
    mparam[$i]="$tmpstr"
  done
}

ircmsgbreak() # facilitate message decomposition
{
  # input:
  #  delimiter string - blank if none
  #  mhead - variable to store extracted value in
  #  mtail - contains the string to be "parsed", 
  #          on return it is the string minus the value
  # model as a queue, this function pops the head of a queue :)

  # copy the tail
  local mtail="$(eval echo \"\$$3\")"

  # handle suffix
  if [[ -n "$1" ]]
  then
    # if there is a suffix we split the head from the tail
    # there is no suffix in $mtail, then mhead is the last item in the queue
    if [[ "$mtail" =~ .*${1}.* ]]
    then
      # first pop the head :)
      local mhead="${mtail%%$1*}"
      # remove head and suffix from tail
      mtail="${mtail#$mhead$1}"
    else
      # no suffix, no more items to pop off
      mhead="$mtail"
      mtail=''
    fi
  fi

  # save values
  read $2 <<<"$mhead"
  read $3 <<<"$mtail"
}

coproc irc { socat -T1000 - "OPENSSL:$server:$port",capath="$capath"; } 2>/dev/null

initstage=true # start in initial stage
nicknum=0      # which nick in nicks is current

while read line
do
  #echo "$line" >> awbot.in.log # DEBUG

  ircmsg # deconstruct message

  if $initstage && [[ "$line" =~ ^: ]]
  then
    # connected to the server
    # first send password
    [[ -n "$pass" ]] && ircwrite "pass $pass"
    # from here on, ignore everything NickServ has to say
    # send nick and user commands
    ircwrite "nick $nicks" "user $ircuser * * $ircname"
    # leave initial stage
    initstage=false
  elif [[ $mcmd == 433 ]]
  then
    # name is in use, choose another
    nicknum=$(( nicknum + 1 ))
    nick="${nicks[$nicknum]}"
    if [[ -z "$nick" ]]
    then
      # out of nicks
      echo error: all nicks are in use >&2
      ircwrite "quit"
      exit
    fi
    ircwrite "nick $nick"
  elif [[ $mcmd == 001 ]]
  then
    # we're free to act
    # why not join a channel? :)
    ircwrite "join $channel"
  #elif [[ $mcmd == 366 ]]
  #then
    # this would be where to put commands to run on joining the channel
  elif [[ $mcmd == PING ]]
  then
    # must respond to PING
    if [[ ${#mparam[@]} == 1 ]] && $mtrailing
    then
      ircwrite "pong :${mparam[0]}" # was trailing
    else
      ircwrite "pong ${mparam[0]}"
    fi
  elif [[ $mcmd == PRIVMSG ]] && [[ "$(enclose01 strip "${mparam[1]}")" == VERSION ]]
  then
    # CTCP VERSION request
    ircwrite "notice $mname :$(enclose01 add "VERSION Arch Linux Women IRC bot")"
  elif [[ "${mparam[0]}" == "$channel" ]] # channel messages
  then
    case "${mcmd^^}" in
      PRIVMSG) # if being addressed by someone, respond
               unset cnick cmsg creply
               read cnick cmsg <<<"${mparam[1]}"
               [[ "$cnick" =~ ^${nick}.?$ ]] &&
               case "$cmsg" in
                    help) creply="The commands are help, about, site, license, and source." ;;
                 license) creply="AGPL https://www.gnu.org/licenses/agpl see also source" ;;
                  source) creply="https://github.com/archwomen/awbot-greeter" ;;
                   about) creply="Hi, I welcome people new to the channel." ;;
                    site) creply="http://redmine.archwomen.org/projects/awbot" ;;
                    ping) creply="pony" ;;
               esac
               [[ -n "$creply" ]] && ircwrite "privmsg $channel :$mname: $creply"
               ;;
         JOIN) sleep 2s ; greet ;; # coproc and child processes confuses me
                                   # is fine if the channel isn't flooded
    esac
  fi
  # no else because other messages are ignored atm
done <&${irc[0]}
