=head1 NAME

awbot-logr - Arch Linux Women IRC logging bot

=head1 SYNOPSIS

awlogr [I<config_options>]

=head1 DESCRIPTION

awbot-logr is a simple IRC robot which logs activity in an IRC channel to systemd-journald. It is a fork of awbot.

Only one channel can be logged at a time. Messages are printed to stdout which are captured by systemd and automatically logged in journald. Only PRIVMSG, NOTICE, PART, JOIN, KICK, MODE, and QUIT messages are logged. To view the logs of #channel, run C<journalctl -au awlogr@channel>.

OpenSSL and socat are required to connect to an IRC server.

=head1 CONFIGURATION

The configuration file is I</etc/awbot.conf>. Configuration can be overridden on the command line by listing options.

=over 4

=item server=

The address of the IRC server to connect to.

=item port=

The port to connect to. This must be the port used for SSL connections.

=item nick=

An IRC nick to use. Upon connection, if the nick is already in use the bot will generate alternative by appending an integer.
 
=item pass=

The corresponding password for the IRC nick. This is optional and can be left blank if there is no password.

Be sure to give the correct password. The bot will ignore NickServ.

B<WARNING> When overriden from the command line, the shell may store the password in a history file.

=item ircname=

A name like a real name.

=item ircuser=

A user name like one used for UNIX accounts. It is optional and if not specified the value for I<nick> is used.

=item channel=

The channel to join and post messages to.

=back

=head1 COPYRIGHT

awbot is copyrighted work. Use `git shortlog -s` to get a list of current authors and contributors and their contact information.

awbot is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.

=head1 WEBSITES

http://archwomen.org

https://github.com/archwomen/awbot-logr
